export type FieldType = 'text' | 'textarea' | 'number' | 'boolean' | 'image' | 'list' | 'select' | 'color';

export interface FieldConfig {
  key: string;
  label: string;
  type: FieldType;
  required?: boolean;
  options?: string[];
}

export interface CollectionConfig {
  key: string;
  table: string;
  label: string;
  idField: string;
  titleField: string;
  fields: FieldConfig[];
}

export const COLLECTIONS: CollectionConfig[] = [
  {
    key: 'products',
    table: 'products',
    label: 'Products',
    idField: 'id',
    titleField: 'name',
    fields: [
      { key: 'id', label: 'ID', type: 'text', required: true },
      { key: 'slug', label: 'Slug', type: 'text', required: true },
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'subtitle', label: 'Subtitle', type: 'text' },
      { key: 'price', label: 'Price', type: 'number', required: true },
      { key: 'original_price', label: 'Original price', type: 'number' },
      { key: 'image', label: 'Image', type: 'image' },
      { key: 'category', label: 'Category', type: 'select', options: ['Wealth & Prosperity', 'Meditation & Clarity', 'Sacred Geometry', 'Ritual & Purification', 'Spiritual Protection'] },
      { key: 'element', label: 'Element', type: 'text' },
      { key: 'element_color', label: 'Element color', type: 'color' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'symbolism', label: 'Symbolism (one per line)', type: 'list' },
      { key: 'quote', label: 'Quote', type: 'textarea' },
      { key: 'vastu_placement', label: 'Vastu placement', type: 'textarea' },
      { key: 'dimensions', label: 'Dimensions', type: 'text' },
      { key: 'material', label: 'Material', type: 'text' },
      { key: 'in_stock', label: 'In stock', type: 'boolean' },
      { key: 'rating', label: 'Rating', type: 'number' },
      { key: 'reviews_count', label: 'Reviews count', type: 'number' },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
      { key: 'published', label: 'Published', type: 'boolean' },
    ],
  },
  {
    key: 'consultations',
    table: 'consultations',
    label: 'Consultations',
    idField: 'id',
    titleField: 'title',
    fields: [
      { key: 'id', label: 'ID', type: 'text', required: true },
      { key: 'slug', label: 'Slug', type: 'text', required: true },
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'tagline', label: 'Tagline', type: 'text' },
      { key: 'short_desc', label: 'Short description', type: 'textarea' },
      { key: 'full_desc', label: 'Full description', type: 'textarea' },
      { key: 'price', label: 'Price', type: 'number', required: true },
      { key: 'duration', label: 'Duration', type: 'text' },
      { key: 'format', label: 'Format', type: 'select', options: ['Online Video / CAD', 'On-Site Visit', 'Hybrid'] },
      { key: 'image', label: 'Image', type: 'image' },
      { key: 'color_hex', label: 'Color', type: 'color' },
      { key: 'deliverables', label: 'Deliverables (one per line)', type: 'list' },
      { key: 'suitable_for', label: 'Suitable for (one per line)', type: 'list' },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
      { key: 'published', label: 'Published', type: 'boolean' },
    ],
  },
  {
    key: 'journal',
    table: 'journal_articles',
    label: 'Journal',
    idField: 'id',
    titleField: 'title',
    fields: [
      { key: 'id', label: 'ID', type: 'text', required: true },
      { key: 'slug', label: 'Slug', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'date', label: 'Date', type: 'text' },
      { key: 'read_time', label: 'Read time', type: 'text' },
      { key: 'image', label: 'Image', type: 'image' },
      { key: 'summary', label: 'Summary', type: 'textarea' },
      { key: 'content', label: 'Content paragraphs (one per line)', type: 'list' },
      { key: 'quote', label: 'Quote', type: 'textarea' },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
      { key: 'published', label: 'Published', type: 'boolean' },
    ],
  },
  {
    key: 'testimonials',
    table: 'testimonials',
    label: 'Testimonials',
    idField: 'id',
    titleField: 'name',
    fields: [
      { key: 'id', label: 'ID', type: 'text', required: true },
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'city', label: 'City', type: 'text' },
      { key: 'property_type', label: 'Property type', type: 'text' },
      { key: 'rating', label: 'Rating', type: 'number' },
      { key: 'comment', label: 'Comment', type: 'textarea', required: true },
      { key: 'date', label: 'Date', type: 'text' },
      { key: 'service', label: 'Service', type: 'text' },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
      { key: 'published', label: 'Published', type: 'boolean' },
    ],
  },
  {
    key: 'directions',
    table: 'directions',
    label: 'Directions',
    idField: 'id',
    titleField: 'name',
    fields: [
      { key: 'code', label: 'Code', type: 'text', required: true },
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'sanskrit_name', label: 'Sanskrit name', type: 'text' },
      { key: 'ruling_deity', label: 'Ruling deity', type: 'text' },
      { key: 'ruling_planet', label: 'Ruling planet', type: 'text' },
      { key: 'element', label: 'Element', type: 'text' },
      { key: 'color_hex', label: 'Color', type: 'color' },
      { key: 'bg_gradient', label: 'Background gradient class', type: 'text' },
      { key: 'key_benefits', label: 'Key benefits', type: 'textarea' },
      { key: 'ideal_for', label: 'Ideal for (one per line)', type: 'list' },
      { key: 'avoid_here', label: 'Avoid here (one per line)', type: 'list' },
      { key: 'remedy_tips', label: 'Remedy tips', type: 'textarea' },
      { key: 'recommended_products', label: 'Recommended product slugs (one per line)', type: 'list' },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
      { key: 'published', label: 'Published', type: 'boolean' },
    ],
  },
  {
    key: 'elements',
    table: 'elements',
    label: 'Five Elements',
    idField: 'id',
    titleField: 'name',
    fields: [
      { key: 'id', label: 'ID', type: 'text', required: true },
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'sanskrit_name', label: 'Sanskrit name', type: 'text' },
      { key: 'zone', label: 'Zone', type: 'text' },
      { key: 'color_hex', label: 'Color', type: 'color' },
      { key: 'bg_light', label: 'Light background', type: 'color' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'qualities', label: 'Qualities (one per line)', type: 'list' },
      { key: 'imbalance_signs', label: 'Imbalance signs', type: 'textarea' },
      { key: 'balancing_action', label: 'Balancing action', type: 'textarea' },
      { key: 'image', label: 'Image', type: 'image' },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
      { key: 'published', label: 'Published', type: 'boolean' },
    ],
  },
  {
    key: 'methodology',
    table: 'methodology_steps',
    label: 'Methodology',
    idField: 'id',
    titleField: 'title',
    fields: [
      { key: 'step', label: 'Step number', type: 'text', required: true },
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'sanskrit_tag', label: 'Sanskrit tag', type: 'text' },
      { key: 'color_hex', label: 'Color', type: 'color' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
      { key: 'published', label: 'Published', type: 'boolean' },
    ],
  },
  {
    key: 'comparisons',
    table: 'methodology_comparisons',
    label: 'Method Comparisons',
    idField: 'id',
    titleField: 'feature',
    fields: [
      { key: 'feature', label: 'Feature', type: 'text', required: true },
      { key: 'traditional', label: 'Traditional approach', type: 'textarea' },
      { key: 'zen_vastu', label: 'Zen Vastu approach', type: 'textarea' },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
    ],
  },
  {
    key: 'about-values',
    table: 'about_values',
    label: 'About Values',
    idField: 'id',
    titleField: 'title',
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'icon', label: 'Icon name', type: 'text' },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
      { key: 'visible', label: 'Visible', type: 'boolean' },
    ],
  },
  {
    key: 'nav',
    table: 'nav_items',
    label: 'Navigation',
    idField: 'id',
    titleField: 'label',
    fields: [
      { key: 'label', label: 'Label', type: 'text', required: true },
      { key: 'section_id', label: 'Section ID', type: 'text', required: true },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
      { key: 'visible', label: 'Visible', type: 'boolean' },
    ],
  },
  {
    key: 'marquee',
    table: 'marquee_items',
    label: 'Marquee',
    idField: 'id',
    titleField: 'text',
    fields: [
      { key: 'text', label: 'Text', type: 'text', required: true },
      { key: 'icon', label: 'Icon name', type: 'text' },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
      { key: 'visible', label: 'Visible', type: 'boolean' },
    ],
  },
  {
    key: 'hero-highlights',
    table: 'hero_highlights',
    label: 'Hero Highlights',
    idField: 'id',
    titleField: 'title',
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'icon', label: 'Icon name', type: 'text' },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
      { key: 'visible', label: 'Visible', type: 'boolean' },
    ],
  },
  {
    key: 'hero-categories',
    table: 'hero_categories',
    label: 'Hero Categories',
    idField: 'id',
    titleField: 'name',
    fields: [
      { key: 'code', label: 'Code', type: 'text', required: true },
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'tag', label: 'Tag', type: 'text' },
      { key: 'icon', label: 'Icon name', type: 'text' },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
      { key: 'visible', label: 'Visible', type: 'boolean' },
    ],
  },
  {
    key: 'footer-links',
    table: 'footer_links',
    label: 'Footer Links',
    idField: 'id',
    titleField: 'label',
    fields: [
      { key: 'group_name', label: 'Group', type: 'text', required: true },
      { key: 'label', label: 'Label', type: 'text', required: true },
      { key: 'section_id', label: 'Section ID', type: 'text' },
      { key: 'url', label: 'External URL', type: 'text' },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
      { key: 'visible', label: 'Visible', type: 'boolean' },
    ],
  },
  {
    key: 'coupons',
    table: 'coupons',
    label: 'Coupons',
    idField: 'id',
    titleField: 'code',
    fields: [
      { key: 'code', label: 'Code', type: 'text', required: true },
      { key: 'discount_percent', label: 'Discount %', type: 'number', required: true },
      { key: 'active', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'time-slots',
    table: 'time_slots',
    label: 'Time Slots',
    idField: 'id',
    titleField: 'label',
    fields: [
      { key: 'label', label: 'Label', type: 'text', required: true },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
      { key: 'visible', label: 'Visible', type: 'boolean' },
    ],
  },
  {
    key: 'property-types',
    table: 'property_types',
    label: 'Property Types',
    idField: 'id',
    titleField: 'label',
    fields: [
      { key: 'label', label: 'Label', type: 'text', required: true },
      { key: 'sort_order', label: 'Sort order', type: 'number' },
      { key: 'visible', label: 'Visible', type: 'boolean' },
    ],
  },
];
